# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      git submodule update --init --recursive
      cat brew.txt | xargs brew install
      pip install --user -r requirements.txt

#
# Run build script
#
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'scripts/build'
    arguments: 'build settings/$(buildConfig)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
